# action.yml
name: "Hello World Action"
description: "A simple GitHub Action that prints Hello, World!"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token for authentication"
    required: true
outputs:
  greeting:
    description: "The greeting message output by the action"
runs:
  using: "node12"
  main: "dist/index.js"
