# action.yml
name: "AI Code Reviewer"
description: "A GitHub Action for code review using AI without an external JavaScript file."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token for authentication"
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for AI model access"
    required: true
  OPENAI_API_MODEL:
    description: "Model to use for AI reviews (e.g., gpt-4)"
    required: false
    default: "gpt-4"
  exclude:
    description: "File patterns to exclude from review"
    required: false
    default: "**/*.json, **/*.md"
runs:
  using: "composite"
  steps:
    - name: Print Hello World
      shell: bash
      run: |
        echo "Hello, World!"
        echo "GITHUB_TOKEN is ${{ inputs.GITHUB_TOKEN }}"
        echo "OPENAI_API_KEY is ${{ inputs.OPENAI_API_KEY }}"
        echo "Using model: ${{ inputs.OPENAI_API_MODEL }}"
        echo "Exclude patterns: ${{ inputs.exclude }}"
